### PR TITLE
Adding JWT Access Token Auth Option

### PR DESCRIPTION
**Pull request by jschroth**
Added option for Access Token. Redone version of PR 268

### CODE REVIEW

**Review by nineinchnick — APPROVED** [review]

**Comment by llamafilm** [comment]
@nineinchnick do you have an idea when this will be included in a release version?  I'm eager to start using this in Grafana Cloud.

**Comment by nineinchnick** [comment]
I still haven't addressed the comments after I submitted 1.0.8. This will be included in 1.0.9, but I can't say when exactly, all the work I do in this repository is voluntary.

**Comment by jschroth** [comment]
@nineinchnick thanks for the work you do. If there is anything we can do to help get 1.0.9 rolled out sooner, please let us know. Thanks again.

**Comment by nineinchnick** [comment]
FYI, I got feedback from Grafana after submitting the plugin for review, and we need to store the access token in `secureJsonData`. I started working on it here: https://github.com/trinodb/grafana-trino/pull/277

**Pull request merged**
